import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedAquipuedesanotarideasrecordatoriosetcWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedAlarmWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedVectorWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedQueharashoyWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedArrow1Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedOpuedesusarlasopcionesdelmenuWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedKeyboard_arrow_downWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedVectorWidget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid4widget/generated/GeneratedSpeaker_notesWidget.dart';

/* Frame Android - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: -10.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 85.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 424.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 34.0,
                child: GeneratedQueharashoyWidget(),
              ),
              Positioned(
                left: 135.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.16666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 60.0;

                  double percentHeight = 0.09375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 60.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4166666666666667,
                        translateY: constraints.maxHeight * 0.8109375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 5.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 61.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 0.0,
                child: GeneratedArrow1Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 117.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 130.0,
                child: GeneratedAquipuedesanotarideasrecordatoriosetcWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.1111111111111111;
                  double scaleX = (constraints.maxWidth * percentWidth) / 40.0;

                  double percentHeight = 0.046875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 30.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4444444444444444,
                        translateY: constraints.maxHeight * 0.715625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget1())
                  ]);
                }),
              ),
              Positioned(
                left: 11.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 66.0,
                child: GeneratedOpuedesusarlasopcionesdelmenuWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedAlarmWidget(),
              ),
              Positioned(
                left: 261.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedSpeaker_notesWidget(),
              ),
              Positioned(
                left: 168.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedKeyboard_arrow_downWidget(),
              )
            ]),
      ),
    ));
  }
}
