import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedLineaWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedVectorWidget15.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/Generated900amWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/Generated840amWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedSpeaker_notesWidget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedAC4Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedAG2Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedReloj1Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedAB2Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedHORARIOSWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedHoradepartidaWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/Generated820amWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedAA1Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedArrow1Widget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/Generated800amWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid7widget/generated/GeneratedAlarmWidget2.dart';

/* Frame Android - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle2Widget2(),
              ),
              Positioned(
                left: -10.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 85.0,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 113.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 37.0,
                child: GeneratedHORARIOSWidget(),
              ),
              Positioned(
                left: 5.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 61.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 98.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 169.0,
                child: GeneratedReloj1Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 0.0,
                child: GeneratedArrow1Widget2(),
              ),
              Positioned(
                left: 135.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedEllipse1Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.16666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 60.0;

                  double percentHeight = 0.09375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 60.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4166666666666667,
                        translateY: constraints.maxHeight * 0.8109375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget15())
                  ]);
                }),
              ),
              Positioned(
                left: 17.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 27.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 199.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 27.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 199.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 27.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 199.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 27.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 199.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 27.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 27.0,
                child: GeneratedRectangle15Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 27.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 269.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 27.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 29.0,
                child: Generated800amWidget(),
              ),
              Positioned(
                left: 255.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 29.0,
                child: GeneratedAC4Widget(),
              ),
              Positioned(
                left: 255.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 29.0,
                child: GeneratedAG2Widget(),
              ),
              Positioned(
                left: 257.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 29.0,
                child: GeneratedAA1Widget(),
              ),
              Positioned(
                left: 255.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 29.0,
                child: GeneratedAB2Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 29.0,
                child: Generated840amWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 29.0,
                child: Generated900amWidget(),
              ),
              Positioned(
                left: 56.0,
                top: 272.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 29.0,
                child: Generated820amWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 26.0,
                child: GeneratedHoradepartidaWidget(),
              ),
              Positioned(
                left: 249.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 29.0,
                child: GeneratedLineaWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedAlarmWidget2(),
              ),
              Positioned(
                left: 261.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedSpeaker_notesWidget2(),
              )
            ]),
      ),
    ));
  }
}
