import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedLineaAB3Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedInsert_emoticonWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedPERFILWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedAlarmWidget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/Generated45aosWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedArrow1Widget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedVicenteFernandezWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedSpeaker_notesWidget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedVectorWidget8.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid5widget/generated/GeneratedRectangle3Widget1.dart';

/* Frame Android - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: -10.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 85.0,
                child: GeneratedRectangle4Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 135.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 37.0,
                child: GeneratedPERFILWidget(),
              ),
              Positioned(
                left: 5.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 61.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 0.0,
                child: GeneratedArrow1Widget1(),
              ),
              Positioned(
                left: 135.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 120.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 120.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.16666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 60.0;

                  double percentHeight = 0.09375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 60.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4166666666666667,
                        translateY: constraints.maxHeight * 0.8109375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget8())
                  ]);
                }),
              ),
              Positioned(
                left: 120.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 120.0,
                child: GeneratedInsert_emoticonWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 43.0,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 19.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 43.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 198.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 43.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 239.0,
                height: 34.0,
                child: GeneratedVicenteFernandezWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 34.0,
                child: Generated45aosWidget(),
              ),
              Positioned(
                left: 211.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 34.0,
                child: GeneratedLineaAB3Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedAlarmWidget1(),
              ),
              Positioned(
                left: 261.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedSpeaker_notesWidget1(),
              )
            ]),
      ),
    ));
  }
}
