import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid2widget/generated/GeneratedBIENVENIDOCONDUCTORWidget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid2widget/generated/GeneratedRectangle2Widget5.dart';

/* Frame Android - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedAndroid1Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -195.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 224.0,
                  height: 640.0,
                  child: GeneratedRectangle2Widget5(),
                ),
                Positioned(
                  left: -327.0,
                  top: 37.0,
                  right: null,
                  bottom: null,
                  width: 329.0,
                  height: 34.0,
                  child: GeneratedBIENVENIDOCONDUCTORWidget2(),
                )
              ]),
        ),
      ),
    ));
  }
}
