import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedRectangle4Widget3.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedEllipse1Widget3.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedEscribeunnuevomensajeWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedNotesWidget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedNotesWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedNotesWidget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedEscribeunnuevomensajeWidget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedArrow1Widget3.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedVectorWidget20.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedAlarmWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedMENSAJESWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedEscribeunnuevomensajeWidget2.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid8widget/generated/GeneratedSpeaker_notesWidget3.dart';

/* Frame Android - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle2Widget3(),
              ),
              Positioned(
                left: -10.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 85.0,
                child: GeneratedRectangle4Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle3Widget3(),
              ),
              Positioned(
                left: 109.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 37.0,
                child: GeneratedMENSAJESWidget(),
              ),
              Positioned(
                left: 5.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 61.0,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 57.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 0.0,
                child: GeneratedArrow1Widget3(),
              ),
              Positioned(
                left: 135.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedEllipse1Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.16666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 60.0;

                  double percentHeight = 0.09375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 60.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4166666666666667,
                        translateY: constraints.maxHeight * 0.8109375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget20())
                  ]);
                }),
              ),
              Positioned(
                left: 8.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 85.0,
                child: GeneratedRectangle13Widget2(),
              ),
              Positioned(
                left: 8.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 85.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 5.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 85.0,
                child: GeneratedRectangle15Widget2(),
              ),
              Positioned(
                left: 38.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedAlarmWidget3(),
              ),
              Positioned(
                left: 261.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedSpeaker_notesWidget3(),
              ),
              Positioned(
                left: 19.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 26.0,
                child: GeneratedEscribeunnuevomensajeWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 26.0,
                child: GeneratedEscribeunnuevomensajeWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 26.0,
                child: GeneratedEscribeunnuevomensajeWidget2(),
              ),
              Positioned(
                left: -24.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 48.0,
                child: GeneratedNotesWidget(),
              ),
              Positioned(
                left: -24.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 48.0,
                child: GeneratedNotesWidget1(),
              ),
              Positioned(
                left: -27.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 48.0,
                child: GeneratedNotesWidget2(),
              )
            ]),
      ),
    ));
  }
}
