import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid3widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid3widget/generated/GeneratedIniciarWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid3widget/generated/GeneratedRectangle3Widget5.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid3widget/generated/GeneratedBIENVENIDOCONDUCTORWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid3widget/generated/GeneratedLogo1Widget.dart';

/* Frame Android - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 640.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 34.0,
                child: GeneratedBIENVENIDOCONDUCTORWidget(),
              ),
              Positioned(
                left: 96.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 188.0,
                child: GeneratedLogo1Widget(),
              ),
              Positioned(
                left: 136.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 78.0,
                child: GeneratedRectangle3Widget5(),
              ),
              Positioned(
                left: 222.0,
                top: 487.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 37.0,
                child: GeneratedIniciarWidget(),
              )
            ]),
      ),
    ));
  }
}
