import 'package:flutter/material.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedVectorWidget31.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedEllipse1Widget4.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedRectangle3Widget4.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedApellidoPWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedVectorWidget32.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedAlarmWidget4.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedSpeaker_notesWidget4.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedArrow2Widget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedNombreWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedRectangle4Widget4.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedRectangle2Widget4.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedREGISTROWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedArrow1Widget4.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedApellidoMWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedEdadWidget.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/proyecto_vivebusapp/generatedandroid6widget/generated/GeneratedRectangle11Widget.dart';

/* Frame Android - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle2Widget4(),
              ),
              Positioned(
                left: -10.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 383.0,
                height: 85.0,
                child: GeneratedRectangle4Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 94.0,
                child: GeneratedRectangle3Widget4(),
              ),
              Positioned(
                left: 116.0,
                top: 31.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 37.0,
                child: GeneratedREGISTROWidget(),
              ),
              Positioned(
                left: 5.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 61.0,
                child: GeneratedRectangle6Widget3(),
              ),
              Positioned(
                left: 290.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 61.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 0.0,
                child: GeneratedArrow1Widget4(),
              ),
              Positioned(
                left: 290.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 0.0,
                child: GeneratedArrow2Widget(),
              ),
              Positioned(
                left: 135.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 89.0,
                child: GeneratedEllipse1Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.16666666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 60.0;

                  double percentHeight = 0.09375;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 60.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4166666666666667,
                        translateY: constraints.maxHeight * 0.8109375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget31())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.3333333333333333;
                  double scaleX = (constraints.maxWidth * percentWidth) / 120.0;

                  double percentHeight = 0.1875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 120.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.3333333333333333,
                        translateY: constraints.maxHeight * 0.1640625,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget32())
                  ]);
                }),
              ),
              Positioned(
                left: 12.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 43.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 37.0,
                child: GeneratedNombreWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 43.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 306.0,
                right: null,
                bottom: null,
                width: 132.0,
                height: 34.0,
                child: GeneratedApellidoPWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 43.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 34.0,
                child: GeneratedApellidoMWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 43.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 37.0,
                child: GeneratedEdadWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedAlarmWidget4(),
              ),
              Positioned(
                left: 261.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedSpeaker_notesWidget4(),
              )
            ]),
      ),
    ));
  }
}
